# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: News
    url: post
    weight: 20
  - name: People
    url: people
    weight: 40  
  - name: Publications
    url: publication
    weight: 50
  - name: Contact
    url: contact
    weight: 80
  - name: Projects
    url: project
    weight: 30
  - name: Teaching
    url: teaching
    weight: 60
  - name: Quick Download
    url: diversity
    weight: 70
  - name: County
    url: static/uploads/CountyCarr.html
    weight: 70
    parent: Quick Download
  - name: Schools
    url: diversity
    weight: 70
    parent: Quick Download
    
